name: CI

on:	
  push:	
    branches: [ master ]	
  pull_request:	
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sfml
      run: |
         sudo apt update
         sudo apt-get install libsfml-dev
    # - name: List files
    #   run: ls
#     - name: Cache
#       uses: actions/cache@v2.1.6
#       with:
    # A list of files, directories, and wildcard patterns to cache and restore
#        path: 
    # An explicit key for restoring and saving the cache
#        key: 
    - name: Build
      run: g++ -o game game.cpp -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
#     - name: C/C++ Lint Action
#       # You may pin to the exact commit or the version.
#       # uses: shenxianpeng/cpp-linter-action@dbace28451a3df0da841873fdb4df0da3d68e52d
#       uses: shenxianpeng/cpp-linter-action@v1.0.0
#     - name: Setup display
#       run: |
#         export DISPLAY=localhost:0
#         echo $DISPLAY
    # - name: Run
    #   run: ./game