name: Testing Project
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  build-and-runs:
    name: build and run
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@master  
      -name: install sfml 
       run:  sudo apt-get install libsfml-dev
      -name: Build code 
       run : g++ -o game game.cpp -lsfml-window -lsfml-system -lsfml-graphics
      -name: output
       run: ./game 
      
