name: learn-github-actions
on: [push]
jobs:
  build-and-runs:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install sfml
        run:  |
        sudo apt update
        sudo apt-get install libsfml-dev 
      - name: Build
        run: g++ -o game game.cpp -lsfml-window -lsfml-graphics -lsfml-system -lsfml-audio
